[package]
name = "nayland"
version = "0.1.1"
license = "BSD-3-Clause"
kind = "Library"
backend = "C"
binaries = []

[toolchain]
version = "2.2.0"

[dependencies]

[platforms.native]
link = ["wayland-client", "wayland-egl", "wayland-egl-backend"]
include = ["wayland-client", "wayland-egl", "wayland-egl-backend"]
